config/routes.rb
Rails.application.routes.draw do
  root 'checks#index'
  get '/login_admin', to: 'main#login_admin'
  resources :logins
  resources :checks
  resources :stores
  resources :employees do
    post :change, on: :member
  end
  resources :reports do
    get :employee, on: :member
  end
   devise_for :users 
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/check.rb
class Check < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  def index; end

  def create
    @employee = Employee.find_by(employee_params)
    if @employee.nil?
      flash[:alert] = 'Wrong number or password'
    else
      @check = Check.new(check_params.merge(timestamp: Time.now.strftime('%H:%M - %F'),
                                            id_employee: @employee.id, id_sucursal: @employee.id_store))
      @check.save ? flash[:notice] = 'Successfully check' : flash[:alert] = 'Checking faill'
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def employee_params
    params.permit(:employee_number, :private_number)
  end

  def check_params
    params.permit(:check)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to '/employees'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      redirect_to '/employees'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path, status: :see_other
  end

  def change
    @employee = Employee.find(params[:id])
    @employee.update(status: params[:status])
    redirect_to ...
  end

  private

  def employee_params
    params.require(:employee).permit(:email, :name, :position, :employee_number, :private_number, :id_store)
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
before_action :authenticate_user!
  def login_admin; end

  def index; end

  def menu; end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def checking_employee; end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @stores = Store.all
    @avgin = []
    @avgout = []
    @stores.each do |store|
      @avgin.append(avg_of_times(Check.select("timestamp").where(id_sucursal: store.id, check: 'in')))
      @avgout.append(avg_of_times(Check.select("timestamp").where(id_sucursal: store.id, check: 'out')))
    end
  end

  def show
    @store = Store.find(params[:id])
    @checks = Check.where(id_sucursal: params[:id])
  end

  def employee
    @employee = Employee.find(params[:id])
    @checks = Check.where(id_employee: params[:id])
  end

  def avg_of_times(array_of_time)
    size = array_of_time.size
    if (size != 0)
      avg_minutes = array_of_time.map do |timestamp|
        timestamp = timestamp.timestamp.strftime("%H:%M")
        hour, minute = timestamp.split(':')
        total_minutes = hour.to_i * 60 + minute.to_i
      end.inject(:+)/size
      horas = (avg_minutes/60).to_s
      minutos = (avg_minutes%60).to_s
      if horas.length == 1 
        horas = "0"+horas
      end
      if minutos.length == 1
        minutos = "0"+minutos
      end
      "#{horas}:#{minutos}"
    else
      0
    end
  end
end 

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  def index
    @stores = Store.all
  end

  def show
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to '/stores'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @store.update(store_params)
      redirect_to '/stores'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_path, status: :see_other
  end

  private

  def store_params
    params.require(:store).permit(:name, :adress)
  end

  def set_store
    @store = Store.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/checks/index.html.erb
<div class="main-container">
  <div class="clock-container">
    <section class="clock">
      <div class="clock-time-container">
        <h1 class="clock-time" id="clock"></h1>
      </div>
    </section>
    <section class="form-container">
      <%= form_with url: checks_path, method: :post do |form| %>
        <div class="input-container">
          <div>
            <%= form.label :employee_number %>
          </div>
          <div>
            <%= form.number_field :employee_number %>
          </div>
        </div>
        <div class="input-container">
          <div>
            <%= form.label :private_number %>
          </div>
          <div>
            <%= form.password_field :private_number%>
          </div>
        </div>
        <div class="message">
          <% flash.each do |key, value| %>
            <div class="message__content <%= key %>">
              <%= value %>
            </div>
          <% end %>
        </div>
        <div class="buttons-container">
          <%= form.button "Check in", name:"check", value:"in" %>
          <%= form.button "Check out", name:"check", value:"out" %>
        </div>
      <% end %>
    </section>
  </div>
</div>

app/views/employee/index.html.erb
Resolving dependencies...
<div class="main-container">
  <div class="add-container">
    <div class="add-button">
      <span> + </span>
    </div>
    <div class="add-text-container">
      <h1>Add new employee</h1>
    </div>
  </div>
  <div class="table-container">
    <section class="header-table">
      <ul>
        <li class="header-table-text">
          <p>Email</p>
        </li>
        <li class="header-table-text">
          <p>Name</p>
        </li>
        <li class="header-table-text">
          <p>Position</p>
        </li>
        <li class="header-table-text">
          <p>Number</p>
        </li>
        <li class="header-table-text">
          <p>Private Number</p>
        </li>
        <li class="header-table-text">
          <p>Actions</p>
        </li>
      </ul>
    </section>
    <% @employees.each do |employee| %>
      <section class="employees-table">
        <ul class= "employees-table-list" >
          <li class="employees-table-cell">
            <p><%= employee.email %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= employee.name %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= employee.position %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= employee.employee_number %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= employee.private_number %></p>
          </li>
          <li class="buttons-container">
            <div>
              <button class="button-edit">Edit</button>
              <button class="button-delete">Delete</button>
            </div>
          </li>
        </ul>
      </section>
    <%end%>
  </section>
</div>
</div>

app/views/employees/_form.html.erb
<%= form_with model: employee do |form| %>
    <div class="info-container">
        <%= form.label :email %><br>
        <%= form.text_field :email, :required => true %>
    </div>
    <div class="info-container">
        <%= form.label :name %><br>
        <%= form.text_field :name, :required => true %>
    </div>
    <div class="info-container">
        <%= form.label :position %><br>
        <%= form.text_field :position, :required => true %>
    </div>
    <div class="info-container">
        <%= form.label :employee_number %><br>
        <%= form.text_field :employee_number, :required => true %>
    </div>
    <div class="info-container">
        <%= form.label :private_number %><br>
        <%= form.text_field :private_number, :required => true %>
    </div>
  <div class="info-container">
    <%= form.label :Store %><br>
    <%= form.select :id_store, Store.all.collect {|p| [p.name, p.id]}, include_blank: true %>
  </div>
    <div class="button-container">
        <%= form.submit %>
    </div>
<% end %>

app/views/employees/edit.html.erb
<div class="main-container">
  <div class="register-container">
    <section class="title-container">
      <h1>Employee edit</h1>
    </section>
    <section class="form-container">
      <%= render "form", employee: @employee %>
    </section>
  </div>
</div>

app/views/employees/index.html.erb
<div class="main-container">
  <div class="add-container">
    <%= link_to new_employee_path do %>
      <div class="add-button">
        <span> + </span>
      </div>
    <% end %>
    <div class="add-text-container">
      <%= link_to "Add new employee" , new_employee_path %>
    </div>
  </div>
  <div class="table-container">
    <section class="header-table">
      <ul>
        <li class="header-table-text">
          <p>Email</p>
        </li>
        <li class="header-table-text">
          <p>Name</p>
        </li>
        <li class="header-table-text">
          <p>Position</p>
        </li>
        <li class="header-table-text ">
          <p>Number</p>
        </li>
        <li class="header-table-text ">
          <p>Private Number</p>
        </li>
        <li class="header-table-text">
          <p>Store</p>
        </li>
        <li class="header-table-text">
          <p>Status</p>
        </li>
        <li class="header-table-text">
          <p>Actions</p>
        </li>
      </ul>
    </section>
    <% @employees.each do |employee| %>
      <section class="employees-table">
        <ul class= "employees-table-list" >
          <li class="employees-table-cell">
            <p><%= employee.email %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= employee.name %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= employee.position %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= employee.employee_number %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= employee.private_number %></p>
          </li>
          <li class="employees-table-cell">
            <p><%=Store.find(employee.id_store).name%></p>
          </li>
          <li class="employees-table-cell">
            <p><%= employee.status %></p>
          </li>
          <li class="buttons-container">
            <div>
              <button class="button-edit"><%= link_to "Edit", edit_employee_path(employee)%></button>
              <% if employee.status == 'Active' %>
                <%= button_to "Inactive", change_employee_path(employee, status: 'Inactive'), method: :post, class: "button-delete" %>
              <% else %>
                <%= button_to "Active", change_employee_path(employee, status: 'Active'), method: :post, class: "button-delete" %>
              <%end%>
            </div>
          </li>
        </ul>
      </section>
    <%end%>
  </section>
</div>
</div>

app/views/employees/new.html.erb
<div class="main-container">
  <div class="register-container">
    <section class="title-container">
      <h1>Employee register</h1>
    </section>
    <section class="form-container">
      <%= render "form", employee: @employee %>
    </section>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Relojchecador</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav>
      <div>
        <%= link_to root_path do %>
          <%= image_tag "logo.svg", class: "logo" %>
        <% end %>
      </div>

      <%if user_signed_in? %>
        <%= current_user.email %>
        <%= link_to destroy_user_session_path, :method => 'delete' do %>
          <button class="nav-button">
            <p>Log out</p>
          </button>
        <% end %>
      <%else%>
        <%= link_to logins_path do %>
          <button class="nav-button">
            <p>Log in</p>
          </button>
        <% end %>
      <% end %>
    </nav>
    <%= yield %>
    <footer>
      <p>© - Team 2 - Iker Toscano,
        Diego Morales,
        Everardo Alcaraz
      </p>
    </footer>
  </body>
</html>

app/views/logins/index.html.erb
<div class="main-container">
  <div class="login-container">
    <section class="title-container">
      <h1>Menu Options</h1>
    </section>
    <section class="form-container">
      <form action="">
        <div class="button-container">
          <%= link_to employees_path do %>
            <button>
              <p>Employees</p>
            </button>
          <% end %>
        </div>
        <div class="button-container">
          <%= link_to stores_path do %>
            <button>
              <p>Stores</p>
            </button>
          <% end %>
        </div>
        <div class="button-container">
          <%= link_to reports_path do %>
            <button>
              <p>Reports</p>
            </button>
          <% end %>
        </div>
      </form>
    </section>
  </div>
</div>

app/views/main/login_admin.html.erb
 <div class="main-container">
        <div class="login-container">
            <section class="title-container">
                <h1>Log-in</h1>
            </section>
            <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
            <section class="form-container">
                <form action="">
                    <div class="info-container">
                        <label for="">Admin</label>
                        <input type="text" name="" id="" placeholder="  Admin name...">
                    </div>
                    <div class="info-container">
                        <label for="">Password</label>
                        <input type="text" name="" id="" placeholder="  Password...">
                    </div>
                   

                    <div class="button-container">
                        <button><p>Login</p></button>
                    </div>
                </form>
            </section>

        </div>

    </div>

app/views/reports/employee.html.erb
<div class="main-container">
    <section class="title-container">
      <h1> <%= @employee.name%> report</h1>
    </section>
  <div class="table-container">
    <section class="header-table">
      <ul>
        <li class="header-table-text">
          <p>Employee</p>
        </li>
        <li class="header-table-text">
          <p>Day</p>
        </li>
        <li class="header-table-text">
          <p>Date</p>
        </li>
        <li class="header-table-text">
          <p>Hour</p>
        </li>
        <li class="header-table-text">
          <p>Check</p>
        </li>
      </ul>
    </section>
    <% @checks.each do |check| %>
      <section class="employees-table">
        <ul class= "employees-table-list" >
          <li class="employees-table-cell">
            <p><%= Employee.find(check.id_employee).name  %></p>
          </li>

          <li class="employees-table-cell">
            <p><%= check.timestamp.strftime("%a") %></p>
          </li>

          <li class="employees-table-cell">
            <p><%= check.timestamp.strftime("%d %b %Y") %></p>
          </li>

          <li class="employees-table-cell">
            <p><%= check.timestamp.strftime("%H:%M") %></p>
          </li>
 
          <li class="employees-table-cell">
            <p><%= check.check %></p>
          </li>
      
        </ul>
      </section>
    <%end%>
  </section>
</div>
</div>

app/views/reports/index.html.erb
<div class="main-container">
    <section class="title-container">
      <h1>Store report</h1>
    </section>
  <div class="table-container">
    <section class="header-table">
      <ul>
        <li class="header-table-text">
          <p>Name</p>
        </li>
        <li class="header-table-text">
          <p>Adress</p>
        </li>
        <li class="header-table-text">
          <p>Employees</p>
        </li>
        <li class="header-table-text">
          <p>Avg. in</p>
        </li>
        <li class="header-table-text">
          <p>Avg. out</p>
        </li>
      </ul>
    </section>
    <% @stores.each_with_index do |store, index| %>
      <section class="employees-table">
        <ul class= "employees-table-list" >
          <li class="employees-table-cell">
            <p><%= store.name %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= store.adress %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= Check.where(id_sucursal: store.id).distinct.pluck(:id_employee).length%></p>
          </li>
          <li class="employees-table-cell">
            <p><%= @avgin[index] %></p>
          </li>
          <li class="employees-table-cell">
            <p><%= @avgout[index] %></p>
          </li>
          <li class="buttons-container">
            <div>
              <button class="button-edit"> <%= link_to "Details" , report_path(store) %></button>
            </div>
          </li>
        </ul>
      </section>
    <%end%>
  </section>
</div>
</div>

app/views/reports/show.html.erb
<div class="main-container">
    <section class="title-container">
      <h1> <%= @store.name%> report</h1>
    </section>
  <div class="table-container">
    <section class="header-table">
      <ul>
        <li class="header-table-text">
          <p>Employee</p>
        </li>
        <li class="header-table-text">
          <p>Day</p>
        </li>
        <li class="header-table-text">
          <p>Date</p>
        </li>
        <li class="header-table-text">
          <p>Hour</p>
        </li>
        <li class="header-table-text">
          <p>Check</p>
        </li>
      </ul>
    </section>
    <% @checks.each do |check| %>
      <section class="employees-table">

        <ul class= "employees-table-list" >

          <li class="employees-table-cell">
            <p><%= Employee.find(check.id_employee).name  %></p>
          </li>

          <li class="employees-table-cell">
            <p><%= check.timestamp.strftime("%a") %></p>
          </li>

          <li class="employees-table-cell">
            <p><%= check.timestamp.strftime("%d %b %Y") %></p>
          </li>

          <li class="employees-table-cell">
            <p><%= check.timestamp.strftime("%H:%M") %></p>
          </li>
 
          <li class="employees-table-cell">
            <p><%= check.check %></p>
          </li>

          <li class="buttons-container">
            <div>
              <button class="button-edit"> <%= link_to "Details" , employee_report_path(check.id_employee) %></button>
            </div>
          </li>
      
        </ul>
      </section>
    <%end%>
  </section>
</div>
</div>

app/views/store/register_store.html.erb
<div class="main-container">
  <div class="register-container">
    <section class="title-container">
      <h1>Store register</h1>
    </section>
    <section class="form-container">
      <form action="">
        <div class="info-container">
          <label for="">Name</label>
          <input type="text" name="" id="" placeholder="  Email...">
        </div>
        <div class="info-container">
          <label for="">Adress</label>
          <input type="text" name="" id="" placeholder="  Name...">
        </div>
        <div class="button-container">
          <button>
            <p>Register</p>
          </button>
        </div>
      </form>
    </section>
  </div>
</div>

app/views/stores/_form.html.erb
 <%= form_with model: @store do |form| %>
  <div class="info-container">
    <%= form.label :name %><br>
    <%= form.text_field :name, :required => true %>
  </div>
  <div class="info-container">
    <%= form.label :adress %><br>
    <%= form.text_field :adress, :required => true %>
  </div>
  <div class="button-container">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<div class="main-container">
  <div class="register-container">
    <section class="title-container">
      <h1>Store edit</h1>
    </section>
    <section class="form-container">
      <%= render "form", store: @store %>
    </section>
  </div>
</div>

app/views/stores/index.html.erb
<div class="main-container">
  <div class="add-container">
    <%= link_to new_store_path do %>
      <div class="add-button">
        <span> + </span>
      </div>
    <% end %>
    <div class="add-text-container">
      <%= link_to "Add new store", new_store_path %>
    </div>
  </div>
  <div class="table-store-container">
    <section class="header-table">
      <ul>
        <li class="header-table-text">
          <p>Store Name</p>
        </li>
        <li class="header-table-text">
          <p>Address</p>
        </li>
        <li class="header-table-text">
          <p>Actions</p>
        </li>
      </ul>
    </section>
    <% @stores.each do |store| %>
      <section class="employees-table">
        <ul>
          <li class="eployees-table-cell">
            <p><%= store.name %></p>
          </li>
          <li class="eployees-table-cell">
            <p><%= store.adress %></p>
          </li>
          <li class="buttons-container">
            <div>
              <button class="button-edit"><%= link_to "Edit", edit_store_path(store)%></button>
              <button class="button-delete"><%= link_to "Delete", store_path(store), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></button>
            </div>
          </li>
        </ul>
      </section>
    <% end %>
  </div>
</div>

app/views/stores/new.html.erb
<div class="main-container">
  <div class="register-container">
    <section class="title-container">
      <h1>Store register</h1>
    </section>
    <section class="form-container">
      <%= render "form", store: @store %>
    </section>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>